# Generated by Django 5.1.6 on 2025-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
